<script>
  import { createEventDispatcher } from "svelte";
  export let borderRadius = "50px";
  export let color = "orange";
  export let animation = "";

  const dispatch = createEventDispatcher();
  let eventName = "contactClicked";
  let evDetail = "Contacto";
</script>

<style>
  button {
    border-radius: 50px;
    padding: 0px;
    border-style: none;
    color: white;
    font-family: "Josefin Sans", sans-serif;
    font-weight: 600;
    /*  META font-size 25px */
    outline: none;
    cursor: pointer;
    box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
    transition: all cubic-bezier(0.165, 0.84, 0.44, 1) 0.65s;
  }

  .orange {
    background: linear-gradient(180deg, #ffbe0b 0%, #ab2626 100%);
  }

  .purple {
    background: linear-gradient(180deg, #ec35f8 0%, #3c26ab 100%);
  }

  .white {
    background: white;
    color: #066d92;
  }

  .blue {
    background: #11a7dd;
    color: white;
  }
  /* 
  button:hover {
    box-shadow: 4px 2px 10px rgba(255, 255, 255, 0.25);
    transform: translateY(-0.15em);
  }

  button:active {
    transform: translateY(-0.5px);
  } */

  /* ----------------------------------------------
 * Generated by Animista on 2020-10-7 10:22:54
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation heartbeat
 * ----------------------------------------
 */

  /* .heartbeat {
    -webkit-animation: heartbeat 3s ease-in-out infinite both;
    animation: heartbeat 3s ease-in-out infinite both;
  }
  @-webkit-keyframes heartbeat {
    from {
      -webkit-transform: scale(1);
      transform: scale(1);
      -webkit-transform-origin: center center;
      transform-origin: center center;
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
    }
    10% {
      -webkit-transform: scale(0.91);
      transform: scale(0.91);
      -webkit-animation-timing-function: ease-in;
      animation-timing-function: ease-in;
    }
    17% {
      -webkit-transform: scale(0.98);
      transform: scale(0.98);
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
    }
    33% {
      -webkit-transform: scale(0.87);
      transform: scale(0.87);
      -webkit-animation-timing-function: ease-in;
      animation-timing-function: ease-in;
    }
    45% {
      -webkit-transform: scale(1);
      transform: scale(1);
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
    }
  }
  @keyframes heartbeat {
    from {
      -webkit-transform: scale(1);
      transform: scale(1);
      -webkit-transform-origin: center center;
      transform-origin: center center;
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
    }
    10% {
      -webkit-transform: scale(0.91);
      transform: scale(0.91);
      -webkit-animation-timing-function: ease-in;
      animation-timing-function: ease-in;
    }
    17% {
      -webkit-transform: scale(0.98);
      transform: scale(0.98);
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
    }
    33% {
      -webkit-transform: scale(0.87);
      transform: scale(0.87);
      -webkit-animation-timing-function: ease-in;
      animation-timing-function: ease-in;
    }
    45% {
      -webkit-transform: scale(1);
      transform: scale(1);
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
    }
  } */
</style>

<button style="border-radius:{borderRadius};" class={`${color} ${animation}`}>
  <slot />
</button>
