const posts = [
  {
    title: "Asesoria",
    author: "Roberto Traspalacio",
    date: "22 de Febrero del 2021",
    image: "/images/service-0.svg",
    tldr: `Consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla.<br>
        <br>
        Consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla.`,
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla. Ipsum quam massa praesent mattis egestas. Elit, ultrices enim, ligula et massa vestibulum. Consequat vitae sed quis sit donec mi. Eget orci, mauris nam sed luctus. Nibh consequat in convallis amet, scelerisque consequat est mi.<br>
        <br>
        Sit volutpat tincidunt aliquet nullam pulvinar. Fusce vitae consequat urna dapibus dui egestas. Urna donec amet volutpat elit pharetra tincidunt eu tortor. At aenean eleifend enim lorem elementum. Ut a quam sed facilisi cursus facilisis odio. Ultricies volutpat faucibus mauris quisque faucibus varius maecenas. Integer vestibulum malesuada et aliquam ultrices at tellus mauris mattis. Nunc id quis facilisi sit odio vel. Mattis augue quis vel nisi massa. Dignissim fames diam id eu. Aliquam, convallis interdum egestas nisi in. Nibh dolor, turpis nunc arcu non dignissim quam. Nibh adipiscing cursus lectus commodo. Sed facilisis orci, fermentum aliquet. Purus sed nunc a facilisi quam amet.<br>
        <br>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla. Ipsum quam massa praesent mattis egestas. Elit, ultrices enim, ligula et massa vestibulum. Consequat vitae sed quis sit donec mi. Eget orci, mauris nam sed luctus. Nibh consequat in convallis amet, scelerisque consequat est mi. Sit volutpat tincidunt aliquet nullam pulvinar. Fusce vitae consequat urna dapibus dui egestas. Urna donec amet volutpat elit pharetra tincidunt eu tortor.`,
  },
  {
    title: "Seudocodigo",
    author: "Rawy Alvarez",
    date: "22 de Febrero del 2022",
    image: "/images/service-1.svg",
    tldr: `Consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla.<br>
        <br>
        Consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla.`,
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla. Ipsum quam massa praesent mattis egestas. Elit, ultrices enim, ligula et massa vestibulum. Consequat vitae sed quis sit donec mi. Eget orci, mauris nam sed luctus. Nibh consequat in convallis amet, scelerisque consequat est mi.<br>
        <br>
        Sit volutpat tincidunt aliquet nullam pulvinar. Fusce vitae consequat urna dapibus dui egestas. Urna donec amet volutpat elit pharetra tincidunt eu tortor. At aenean eleifend enim lorem elementum. Ut a quam sed facilisi cursus facilisis odio. Ultricies volutpat faucibus mauris quisque faucibus varius maecenas. Integer vestibulum malesuada et aliquam ultrices at tellus mauris mattis. Nunc id quis facilisi sit odio vel. Mattis augue quis vel nisi massa. Dignissim fames diam id eu. Aliquam, convallis interdum egestas nisi in. Nibh dolor, turpis nunc arcu non dignissim quam. Nibh adipiscing cursus lectus commodo. Sed facilisis orci, fermentum aliquet. Purus sed nunc a facilisi quam amet.<br>
        <br>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla. Ipsum quam massa praesent mattis egestas. Elit, ultrices enim, ligula et massa vestibulum. Consequat vitae sed quis sit donec mi. Eget orci, mauris nam sed luctus. Nibh consequat in convallis amet, scelerisque consequat est mi. Sit volutpat tincidunt aliquet nullam pulvinar. Fusce vitae consequat urna dapibus dui egestas. Urna donec amet volutpat elit pharetra tincidunt eu tortor.`,
  },
  {
    title: "UI UX",
    author: "Paris",
    date: "22 de Febrero del 2020",
    image: "/images/service-2.svg",
    tldr: `Consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla.<br>
        <br>
        Consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla.`,
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla. Ipsum quam massa praesent mattis egestas. Elit, ultrices enim, ligula et massa vestibulum. Consequat vitae sed quis sit donec mi. Eget orci, mauris nam sed luctus. Nibh consequat in convallis amet, scelerisque consequat est mi.<br>
        <br>
        Sit volutpat tincidunt aliquet nullam pulvinar. Fusce vitae consequat urna dapibus dui egestas. Urna donec amet volutpat elit pharetra tincidunt eu tortor. At aenean eleifend enim lorem elementum. Ut a quam sed facilisi cursus facilisis odio. Ultricies volutpat faucibus mauris quisque faucibus varius maecenas. Integer vestibulum malesuada et aliquam ultrices at tellus mauris mattis. Nunc id quis facilisi sit odio vel. Mattis augue quis vel nisi massa. Dignissim fames diam id eu. Aliquam, convallis interdum egestas nisi in. Nibh dolor, turpis nunc arcu non dignissim quam. Nibh adipiscing cursus lectus commodo. Sed facilisis orci, fermentum aliquet. Purus sed nunc a facilisi quam amet.<br>
        <br>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla. Ipsum quam massa praesent mattis egestas. Elit, ultrices enim, ligula et massa vestibulum. Consequat vitae sed quis sit donec mi. Eget orci, mauris nam sed luctus. Nibh consequat in convallis amet, scelerisque consequat est mi. Sit volutpat tincidunt aliquet nullam pulvinar. Fusce vitae consequat urna dapibus dui egestas. Urna donec amet volutpat elit pharetra tincidunt eu tortor.`,
  },
  {
    title: "Desarrollo",
    author: "Paris",
    date: "22 de Febrero del 2020",
    image: "/images/service-3.svg",
    tldr: `Consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla.<br>
        <br>
        Consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla.`,
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla. Ipsum quam massa praesent mattis egestas. Elit, ultrices enim, ligula et massa vestibulum. Consequat vitae sed quis sit donec mi. Eget orci, mauris nam sed luctus. Nibh consequat in convallis amet, scelerisque consequat est mi.<br>
        <br>
        Sit volutpat tincidunt aliquet nullam pulvinar. Fusce vitae consequat urna dapibus dui egestas. Urna donec amet volutpat elit pharetra tincidunt eu tortor. At aenean eleifend enim lorem elementum. Ut a quam sed facilisi cursus facilisis odio. Ultricies volutpat faucibus mauris quisque faucibus varius maecenas. Integer vestibulum malesuada et aliquam ultrices at tellus mauris mattis. Nunc id quis facilisi sit odio vel. Mattis augue quis vel nisi massa. Dignissim fames diam id eu. Aliquam, convallis interdum egestas nisi in. Nibh dolor, turpis nunc arcu non dignissim quam. Nibh adipiscing cursus lectus commodo. Sed facilisis orci, fermentum aliquet. Purus sed nunc a facilisi quam amet.<br>
        <br>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla. Ipsum quam massa praesent mattis egestas. Elit, ultrices enim, ligula et massa vestibulum. Consequat vitae sed quis sit donec mi. Eget orci, mauris nam sed luctus. Nibh consequat in convallis amet, scelerisque consequat est mi. Sit volutpat tincidunt aliquet nullam pulvinar. Fusce vitae consequat urna dapibus dui egestas. Urna donec amet volutpat elit pharetra tincidunt eu tortor.`,
  },
  {
    title: "Optimizacion",
    author: "Paris",
    date: "22 de Febrero del 2020",
    image: "/images/service-4.svg",
    tldr: `Consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla.<br>
        <br>
        Consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla.`,
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla. Ipsum quam massa praesent mattis egestas. Elit, ultrices enim, ligula et massa vestibulum. Consequat vitae sed quis sit donec mi. Eget orci, mauris nam sed luctus. Nibh consequat in convallis amet, scelerisque consequat est mi.<br>
        <br>
        Sit volutpat tincidunt aliquet nullam pulvinar. Fusce vitae consequat urna dapibus dui egestas. Urna donec amet volutpat elit pharetra tincidunt eu tortor. At aenean eleifend enim lorem elementum. Ut a quam sed facilisi cursus facilisis odio. Ultricies volutpat faucibus mauris quisque faucibus varius maecenas. Integer vestibulum malesuada et aliquam ultrices at tellus mauris mattis. Nunc id quis facilisi sit odio vel. Mattis augue quis vel nisi massa. Dignissim fames diam id eu. Aliquam, convallis interdum egestas nisi in. Nibh dolor, turpis nunc arcu non dignissim quam. Nibh adipiscing cursus lectus commodo. Sed facilisis orci, fermentum aliquet. Purus sed nunc a facilisi quam amet.<br>
        <br>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla. Ipsum quam massa praesent mattis egestas. Elit, ultrices enim, ligula et massa vestibulum. Consequat vitae sed quis sit donec mi. Eget orci, mauris nam sed luctus. Nibh consequat in convallis amet, scelerisque consequat est mi. Sit volutpat tincidunt aliquet nullam pulvinar. Fusce vitae consequat urna dapibus dui egestas. Urna donec amet volutpat elit pharetra tincidunt eu tortor.`,
  },
  {
    title: "Mantenimiento",
    author: "Paris",
    date: "22 de Febrero del 2020",
    image: "/images/service-5.svg",
    tldr: `Consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla.<br>
        <br>
        Consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla.`,
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla. Ipsum quam massa praesent mattis egestas. Elit, ultrices enim, ligula et massa vestibulum. Consequat vitae sed quis sit donec mi. Eget orci, mauris nam sed luctus. Nibh consequat in convallis amet, scelerisque consequat est mi.<br>
        <br>
        Sit volutpat tincidunt aliquet nullam pulvinar. Fusce vitae consequat urna dapibus dui egestas. Urna donec amet volutpat elit pharetra tincidunt eu tortor. At aenean eleifend enim lorem elementum. Ut a quam sed facilisi cursus facilisis odio. Ultricies volutpat faucibus mauris quisque faucibus varius maecenas. Integer vestibulum malesuada et aliquam ultrices at tellus mauris mattis. Nunc id quis facilisi sit odio vel. Mattis augue quis vel nisi massa. Dignissim fames diam id eu. Aliquam, convallis interdum egestas nisi in. Nibh dolor, turpis nunc arcu non dignissim quam. Nibh adipiscing cursus lectus commodo. Sed facilisis orci, fermentum aliquet. Purus sed nunc a facilisi quam amet.<br>
        <br>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla. Ipsum quam massa praesent mattis egestas. Elit, ultrices enim, ligula et massa vestibulum. Consequat vitae sed quis sit donec mi. Eget orci, mauris nam sed luctus. Nibh consequat in convallis amet, scelerisque consequat est mi. Sit volutpat tincidunt aliquet nullam pulvinar. Fusce vitae consequat urna dapibus dui egestas. Urna donec amet volutpat elit pharetra tincidunt eu tortor.`,
  },
  {
    title: "Wordpress",
    author: "Viviana Mendoza",
    date: "22 de Febrero del 2020",
    image: "/images/product-0.svg",
    tldr: `Consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla.<br>
        <br>
        Consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla.`,
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla. Ipsum quam massa praesent mattis egestas. Elit, ultrices enim, ligula et massa vestibulum. Consequat vitae sed quis sit donec mi. Eget orci, mauris nam sed luctus. Nibh consequat in convallis amet, scelerisque consequat est mi.<br>
        <br>
        Sit volutpat tincidunt aliquet nullam pulvinar. Fusce vitae consequat urna dapibus dui egestas. Urna donec amet volutpat elit pharetra tincidunt eu tortor. At aenean eleifend enim lorem elementum. Ut a quam sed facilisi cursus facilisis odio. Ultricies volutpat faucibus mauris quisque faucibus varius maecenas. Integer vestibulum malesuada et aliquam ultrices at tellus mauris mattis. Nunc id quis facilisi sit odio vel. Mattis augue quis vel nisi massa. Dignissim fames diam id eu. Aliquam, convallis interdum egestas nisi in. Nibh dolor, turpis nunc arcu non dignissim quam. Nibh adipiscing cursus lectus commodo. Sed facilisis orci, fermentum aliquet. Purus sed nunc a facilisi quam amet.<br>
        <br>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla. Ipsum quam massa praesent mattis egestas. Elit, ultrices enim, ligula et massa vestibulum. Consequat vitae sed quis sit donec mi. Eget orci, mauris nam sed luctus. Nibh consequat in convallis amet, scelerisque consequat est mi. Sit volutpat tincidunt aliquet nullam pulvinar. Fusce vitae consequat urna dapibus dui egestas. Urna donec amet volutpat elit pharetra tincidunt eu tortor.`,
  },
  {
    title: "Headless Wordpress",
    author: "Paris",
    date: "22 de Febrero del 2020",
    image: "/images/product-1.svg",
    tldr: `Consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla.<br>
        <br>
        Consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla.`,
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla. Ipsum quam massa praesent mattis egestas. Elit, ultrices enim, ligula et massa vestibulum. Consequat vitae sed quis sit donec mi. Eget orci, mauris nam sed luctus. Nibh consequat in convallis amet, scelerisque consequat est mi.<br>
        <br>
        Sit volutpat tincidunt aliquet nullam pulvinar. Fusce vitae consequat urna dapibus dui egestas. Urna donec amet volutpat elit pharetra tincidunt eu tortor. At aenean eleifend enim lorem elementum. Ut a quam sed facilisi cursus facilisis odio. Ultricies volutpat faucibus mauris quisque faucibus varius maecenas. Integer vestibulum malesuada et aliquam ultrices at tellus mauris mattis. Nunc id quis facilisi sit odio vel. Mattis augue quis vel nisi massa. Dignissim fames diam id eu. Aliquam, convallis interdum egestas nisi in. Nibh dolor, turpis nunc arcu non dignissim quam. Nibh adipiscing cursus lectus commodo. Sed facilisis orci, fermentum aliquet. Purus sed nunc a facilisi quam amet.<br>
        <br>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla. Ipsum quam massa praesent mattis egestas. Elit, ultrices enim, ligula et massa vestibulum. Consequat vitae sed quis sit donec mi. Eget orci, mauris nam sed luctus. Nibh consequat in convallis amet, scelerisque consequat est mi. Sit volutpat tincidunt aliquet nullam pulvinar. Fusce vitae consequat urna dapibus dui egestas. Urna donec amet volutpat elit pharetra tincidunt eu tortor.`,
  },
  {
    title: "Paginas a medidas",
    author: "Rawy Alvarez",
    date: "22 de Febrero del 2021",
    image: "/images/product-2.svg",
    tldr: `Consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla.<br>
        <br>
        Consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla.`,
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla. Ipsum quam massa praesent mattis egestas. Elit, ultrices enim, ligula et massa vestibulum. Consequat vitae sed quis sit donec mi. Eget orci, mauris nam sed luctus. Nibh consequat in convallis amet, scelerisque consequat est mi.<br>
        <br>
        Sit volutpat tincidunt aliquet nullam pulvinar. Fusce vitae consequat urna dapibus dui egestas. Urna donec amet volutpat elit pharetra tincidunt eu tortor. At aenean eleifend enim lorem elementum. Ut a quam sed facilisi cursus facilisis odio. Ultricies volutpat faucibus mauris quisque faucibus varius maecenas. Integer vestibulum malesuada et aliquam ultrices at tellus mauris mattis. Nunc id quis facilisi sit odio vel. Mattis augue quis vel nisi massa. Dignissim fames diam id eu. Aliquam, convallis interdum egestas nisi in. Nibh dolor, turpis nunc arcu non dignissim quam. Nibh adipiscing cursus lectus commodo. Sed facilisis orci, fermentum aliquet. Purus sed nunc a facilisi quam amet.<br>
        <br>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor vestibulum proin tempor eget amet volutpat tortor nunc. In tortor, ornare lobortis sit feugiat volutpat. Risus ut libero pellentesque praesent sociis in lorem sapien sit. Gravida cras enim dui ullamcorper pharetra, varius. Ridiculus aliquam, enim, amet, pretium felis et. Porttitor egestas nec bibendum amet mattis integer. Lectus turpis aliquet lectus ipsum lectus. Auctor lobortis ac nisl porttitor faucibus blandit nunc nisl enim. Eget odio quam fusce sit malesuada tempus fringilla. Ipsum quam massa praesent mattis egestas. Elit, ultrices enim, ligula et massa vestibulum. Consequat vitae sed quis sit donec mi. Eget orci, mauris nam sed luctus. Nibh consequat in convallis amet, scelerisque consequat est mi. Sit volutpat tincidunt aliquet nullam pulvinar. Fusce vitae consequat urna dapibus dui egestas. Urna donec amet volutpat elit pharetra tincidunt eu tortor.`,
  },
];

export { posts };
